### ISSUE TITLE
add phone number to 'if found' message

### ISSUE THREAD

**Issue by tomhoover** [MikeMcQuaid/strap#100]
I'd like to submit a patch to allow for an optional phone number to be appended to the 'if found' message:

"Found this computer? Please contact $STRAP_GIT_NAME at $STRAP_GIT_EMAIL **or $STRAP_PHONE**."

Before creating the patch:

1. Is this something you'd consider adding?
2. If so, what is your preference for entering the phone number?
    - require the user to edit strap.sh to set the appropriate variable?
    - pass an environment variable to the script?
    - prompt the user for the (optional) phone number?
    - or ???

**Comment by MikeMcQuaid** [comment]
I'd rather not add this because of the desire to keep this script from prompting users on installation time (configuration should be organisation rather than user specific).
