### ISSUE TITLE
Permission Issue with script/setup

### ISSUE THREAD

**Issue by john-kelly** [MikeMcQuaid/strap#101]
I ran in debug mode and got this where script/setup is supposed to run. It looks like the `-x` check is failing. I'm unsure what the issue is! Any insight would help.

I'm running on macOS Sierra 10.12.4 

```
+ cd /Users/john-kelly/.dotfiles
+ for i in script/setup script/bootstrap
+ '[' -f script/setup ']'
+ '[' -x script/setup ']'
+ for i in script/setup script/bootstrap
+ '[' -f script/bootstrap ']'
+ logk
+ STRAP_STEP=
+ echo OK
OK
```

**Comment by john-kelly** [comment]
I believe I resolved this. I was unaware that changing the permissions of the file is something that could be committed! Very interesting. 

For anyone who runs into this in the future:
http://stackoverflow.com/questions/12276507/run-script-on-mac-prompt-permission-denied

**Comment by MikeMcQuaid** [comment]
Glad you got it sorted.
