### ISSUE TITLE
usability issue for organizations

### ISSUE THREAD

**Issue by AlJohri** [MikeMcQuaid/strap#105]
Hi @MikeMcQuaid. I want to start using strap + homebrew brewfiles at my company. I basically want a very minimal brewfile and a couple extra shell commands to install the right version of python and ruby, use homebrew openssl during the installs, set up bundler for ruby, and virtualenv for python, etc.

I can have people fork an org-wide `homebrew-brewfile` and run strap, but I'd then have to have them run a custom postinstall script.

I can have people fork an org-wide `dotfiles` repository but that's a very personal thing for a lot of people. I understand that all they need is a `setup/script` file but this definitely seems like a barrier to entry.

**What I want**: an org-wide repository I can have users fork and then blissfully run strap with no extra steps.

**Potential solution**: Allow for a file called `postinstall` or `setup` or `bootstrap` within the `homebrew-brewfile` repository. With the addition of the `bundle check` I think having both a `homebrew-brewfile` repository and a `dotfiles` can actually be a great thing. It always felt a tad weird having my "set up python and ruby" scripts in dotfiles where it felt more like a place to "symlink all the things".

I'm not tied to any solution but I think this is real usability issue. I'd love to hear your thoughts. Thanks!

**Comment by MikeMcQuaid** [comment]
Note Strap is already used by multiple organisations including GitHub. The solution to this problem is not having a single Brewfile that's run by everyone in your organisation but having Brewfile's in the relevant repositories for projects. For example, if you have someone who only works on Ruby applications: why do they need virtualenv for Python (and vice-versa). This is the main issue I have with pretty much all of Strap's competitors (assuming everyone in an organisation needs all these packages) so I'm afraid it's not a solution Strap is ever going to adopt.

These repos may be helpful in seeing how GitHub shares these scripts between projects:
https://github.com/github/homebrew-bootstrap/
https://github.com/github/scripts-to-rule-them-all/
https://github.com/ossfriday/ossfriday/blob/master/Brewfile

**Comment by AlJohri** [comment]
woah this https://github.com/github/homebrew-bootstrap/ is super cool. I've been wondering an efficient way to share bash scripts across repositories. I'm already trying the project specific brewfiles and those are working quite well. thanks for the examples!

my main thought was that normalizing the way everyone runs python in an organization via pyenv, for example, makes it easier down the line when you are trying to run someone else's project locally. my project bootstrap script can create a virtualenv, install the correct dependencies, etc. without having to do crazy bash fu to be able to be cross compatible with homebrew python, pyenv python, system python etc.

have you run into any thing like that? like, an rvm user at Github that has to switch to rbenv when switching to someone else's project?

**Comment by MikeMcQuaid** [comment]
> have you run into any thing like that? like, an rvm user at Github that has to switch to rbenv when switching to someone else's project?

We use `rbenv` for detecting Ruby versions but as long as `.ruby-version` and `which ruby` agree we don't mandate what application is used. You can see this here: https://github.com/github/homebrew-bootstrap/blob/master/cmd/brew-bootstrap-rbenv-ruby

**Comment by AlJohri** [comment]
we ran into similar situation where a new employee used the enterprise postgres installer where some of our project specific Brewfiles install the homebrew postgres and try to restart the service with launchctl. it took longer than expected to get rid of the enterprise postgres sinice it has a weird custom uninstall script

i'll look into this a bit more but it seems like a couple mandates regarding how to install your pythons, rubies, databases etc. just make it easier for the organization in the long run

**Comment by MikeMcQuaid** [comment]
> i'll look into this a bit more but it seems like a couple mandates regarding how to install your pythons, rubies, databases etc. just make it easier for the organization in the long run

You can mandate all that stuff in project-specific/shared scripts and in `Brewfile`s. That's what we do.

**Comment by AlJohri** [comment]
after reading https://github.com/boxen/boxen/issues/213#issuecomment-297331709 I understand your point a bit better and see some of the issues with org-wide Brewfiles. sometimes it's hard to imagine why everyone wouldn't want to replicate my perfect setup ™ on their machine 🤓

**Comment by MikeMcQuaid** [comment]
Thanks. It's not always easy to explain this stuff. My high-level view is that system administrators making users install software they aren't going to use 100% of is a bad idea.
