### ISSUE TITLE
404 https://macos-strap.herokuapp.com/strap.sh

### ISSUE THREAD

**Issue by zhenkyle** [MikeMcQuaid/strap#109]
When I open:

    https://macos-strap.herokuapp.com

and click `Download the strap.sh`,  then page is redirected to:

    https://osx-strap.herokuapp.com/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=25c3cfbd9b61a97836f4e9b082b0c24b7bae05e8aef95d27

Screen shot:

![screen shot 2017-07-07 at 9 25 44 pm](https://user-images.githubusercontent.com/494623/27959650-e0adafde-635a-11e7-86e4-2923ecd09e2e.png)

---

Just another question:

I found this URL from somewhere:

    https://strap.githubapp.com/strap.sh

Is this a vanilla version everybody can use or a version just for Github company guys? 

I notice the url to file an issue is:
    
    https://github.com/github/strap-internal/issues/new

So I dare not to use it.

**Comment by MikeMcQuaid** [comment]
This should be fixed now, let me know if it isn't. Thanks!
