### ISSUE TITLE
defaults write domains no longer valid in Sierra

### ISSUE THREAD

**Issue by sporkd** [MikeMcQuaid/strap#110]
In stock Sierra, `defaults read com.apple` now returns `Domain com.apple does not exist`. In the best case scenario, the changes are just not taking. But a worst case scenario is that it's wrongly updating the System Preference UI elements without actually changing the setting. See StackExchange report below:

https://apple.stackexchange.com/questions/259820/macos-sierra-breaks-a-lot-of-terminal-defaults-write-commands-tap-to-click-fo

**Comment by MikeMcQuaid** [comment]
Thanks for the report, will dig more into this.

**Comment by MikeMcQuaid** [comment]
I've looked into this further and I'm not sure I see what's actionable here, sorry. If you can confirm that something is definitely broken and provide a reproducible test case then I can look at fixing it.
