### ISSUE TITLE
xcodebuild requires Xcode

### ISSUE THREAD

**Issue by nhessler** [MikeMcQuaid/strap#111]
I'm trying to run the install script and I'm getting this error then script aborts during `xcode_license`. Here is the error I'm getting

`xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance`

Seems they want me to install the Xcode App. No problem installing it, but I just want to make sure it's a necessary dependency to get things working. If so, maybe this should be noted in the README.

**Comment by MikeMcQuaid** [comment]
What version of macOS are you on? Did you have anything already installed on your machine or run in your terminal before running Strap? Thanks!

**Comment by nhessler** [comment]
I'm on Sierra and I'm running this on a brand new VM. nothing done except running this script

**Comment by MikeMcQuaid** [comment]
Cool, thanks.

**Comment by MikeMcQuaid** [comment]
So, it seems your `/usr/bin/xcrun clang 2>&1` contains the string "license" in the output to reach that stage. Can you confirm whether or not that's the case and any ideas what may have caused that? It sounds like you maybe did have an old version of Xcode around somewhere with the license not agreed somewhere, is that possible?

**Comment by nhessler** [comment]
This is the error I get when I run that command.

```shell
$ /usr/bin/xcrun clang 2>&1
clang: error: no input files
```

**Comment by MikeMcQuaid** [comment]
Hmm, not sure what I'm missing here because:

https://github.com/MikeMcQuaid/strap/blob/c72f36595f0f2160d017750a5e14f61825105731/bin/strap.sh#L149-L157

You can see it's only going to run `xcodebuild` if that line matches `license`.

**Comment by nhessler** [comment]
so to make sure I understand, the clang error is expected, and needing to accept the XCode license needs to happen only if Xcode is installed?

**Comment by MikeMcQuaid** [comment]
Yeh; if `clang`'s has the word `license` in it: you need to confirm the Xcode license.

**Comment by nhessler** [comment]
cool. thanks! sorry for the confusion.

**Comment by MikeMcQuaid** [comment]
No worries!
