### ISSUE TITLE
macOS High Sierra 10.13 support ?

### ISSUE THREAD

**Issue by qkdreyer** [MikeMcQuaid/strap#112]

**Comment by MikeMcQuaid** [comment]
Closing this until there's a clearer question.

**Comment by qkdreyer** [comment]
Sorry for being that unclear.
It's impossible to use strap.sh because of this check : 

'''
sw_vers -productVersion | grep $Q -E "^10.(9|10|11|12)" || {
  abort "Run Strap on macOS 10.9/10/11/12."
}
'''

**Comment by MikeMcQuaid** [comment]
Ok, thanks. It should just work as-is on 10.13. Can you submit a pull request to update that check and see if it does (even if it's just a test on an already-strapped system)? Thanks!
