### ISSUE TITLE
xcode license agreement expect user interaction

### ISSUE THREAD

**Issue by blackjid** [MikeMcQuaid/strap#117]
Today I run strap in an already strapped machine because at least my xcode license was not agreed anymore (not sure if xcode was upgraded or the term changed)

I'm not sure I strap is meant to be completely non-interactive or no

I'm getting stuck here, forcing me to read and manually accept the terms..

```
--> Enter your password (for sudo access):
Password:
OK
--> Configuring security settings: OK
--> Checking full-disk encryption status: OK
--> Asking for Xcode license confirmation:

You have not agreed to the Xcode license agreements. You must agree to both license agreements below in order to use Xcode.

Hit the Enter key to view the license agreements at '/Applications/Xcode.app/Contents/Resources/English.lproj/License.rtf'
```

I think this line is the one that is expecting user interaction
https://github.com/MikeMcQuaid/strap/blob/master/bin/strap.sh#L152

**Comment by blackjid** [comment]
@MikeMcQuaid 

If https://github.com/MikeMcQuaid/strap/blob/master/bin/strap.sh#L152 is changed to use `xcodebuild -license accept` it works fine. But again, I don't know if the intention is to have the user to accept manually or not.

**Comment by MikeMcQuaid** [comment]
@blackjid Is that flag available on older versions of macOS or Xcode. 

> I'm not sure I strap is meant to be completely non-interactive or no

It's intended to be non-interactive when possible so it'd be great to have a PR to add this if it's around on older versions.

**Comment by MikeMcQuaid** [comment]
Let's keep talking here but I don't consider this a bug with Strap itself so closing for now. Would love to see a PR if this is something that still works on older versions (or can be guarded on them), though.
