### ISSUE TITLE
Strap doesn't work in virtual machines

### ISSUE THREAD

**Issue by evanrlong** [MikeMcQuaid/strap#118]
Running Strap in a VirtualBox vm (with a fresh install of macOS Sierra) causes the vm to become unbootable after restart.  The culprit seems to be full disk encryption.  Commenting out the portion of strap.sh which activates fde fixes the problem.  

I have a couple of ideas on how to address this issue, but they would both involve selectively disabling fde, which violates the rule of not deactivating security features, so I figured I would start a discussion before creating a pull request.  It would be great if Strap could be run on a vm without user modification so that people can try it out before committing.

**Option 1:**
Add a --vm flag to the strap.sh script.  With this option, Strap would not enable fde or other features that conflict with running in a virtual environment.  This option would require users to opt in to disabling fde so it could not accidentally be triggered.  The downside is if a user forgets to pass the flag in while on a vm, the vm will be broken.

**Option 2:**
Use something like [this](https://stackoverflow.com/a/28649534) to detect if a macOS is running in a vm, and automatically disable fde if true.  This would be the more automatic option, but I haven't fully tested the vm detection to see how robust it would be.

I will happily put together a pull request if something like this is of interest.

**Comment by MikeMcQuaid** [comment]
Thanks for the detailed write-up but this is beyond the scope I want to take for the Strap project. That Strap works on VMs seems sufficient given VMs snapshot capabilities.

**Comment by AlJohri** [comment]
https://github.com/MikeMcQuaid/strap/issues/67 seems like you are/were amenable to an environment variable to disable the firewall some time back? perhaps that could be an alternative to `--vm`

would help my use case as well :)

**Comment by MikeMcQuaid** [comment]
I'd rather keep Strap opinonated and focused on what it does well. Additional configuration makes it harder to maintain and support and adds more potential for things to break.

**Comment by evanrlong** [comment]
I completely understand your desire to not increase configuration complexity.  At the very least, could we get a comment added to the README to warn users that Strap will not run properly on VMs without commenting out the fde section of the script?  Otherwise, users like me who prefer to test scripts that majorly impact their system in a VM before running it on their main machine will run into problems and might assume that Strap is not functioning properly.

**Comment by MikeMcQuaid** [comment]
@evanrlong I'd rather see a few more people hit this issue before noting it in the README. The README does state the FDE will be enabled and that hasn't broken my VMware VMs in the past when testing Strap there.
