### ISSUE TITLE
Keeping sudo auth alive not working in Sierra / High Sierra

### ISSUE THREAD

**Issue by sihil** [MikeMcQuaid/strap#123]
Apple updated sudo from `1.7.10p9` to `1.8.17p1` in macOS 10.12 / 10.13. In `1.8.10` sudo changed the way that the timestamps were modelled:
> The sudoers plugin uses a new format for its time stamp files. Each user now has a single file which may contain multiple records when per-tty time stamps are in use (the default). The time stamps use a monotonic timer where available and are once again located in a directory under /var/run. The lecture status is now stored separately from the time stamps in a different directory. [Bug #616](http://bugzilla.sudo.ws/show_bug.cgi?id=616).

https://www.sudo.ws/stable.html#1.8.10

On both Sierra and High Sierra `sudo -V` (as root) tells us that the `Path to authentication timestamp dir: /var/db/sudo/ts`. Under this directory is a `$USER` file that contains binary data.

As a result of this the creative mechanism for keeping the sudo session alive no longer works in the Sierra lineup. There doesn't seem to be a quick fix from what I can tell. Since the timestamp is now stored inside the file so it is no longer possible to use `touch` to update it.

I'm afraid I've not yet experimented with alternatives, but it might be worth seeing if `sudo -v` works again.

**Comment by MikeMcQuaid** [comment]
Thanks for the report. 

> but it might be worth seeing if sudo -v works again.

Agreed.
