### ISSUE TITLE
Enable limited SSHD by default?

### ISSUE THREAD

**Issue by dnwe** [mikemcquaid/strap#14]
Something along the lines of using the [keys](https://developer.github.com/v3/users/keys/) api to retrieve public key(s) from your GH profile, and then the following in strap.sh

```
mkdir -p ~/.ssh
chmod 0700 ~/.ssh
cat >> ~/.ssh/authorized_keys <<EOF
$STRAP_GITHUB_SSH_PUBLIC_KEY $STRAP_GITHUB_SSH_PUBLIC_TITLE
EOF
chmod 0600 ~/.ssh/authorized_keys

sudo tee /etc/sshd_config <<EOF
SyslogFacility AUTHPRIV
LogLevel VERBOSE
PubkeyAuthentication yes
AuthorizedKeysFile	.ssh/authorized_keys
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM no
UseDNS no
PermitEmptyPasswords no
LoginGraceTime 1m
PermitRootLogin no
UsePrivilegeSeparation sandbox
Subsystem sftp /usr/libexec/sftp-server
EOF

systemsetup -setremotelogin on

```

**Comment by mikemcquaid** [comment]
I'd rather not overwrite the system configuration as-is. Can you detail what you've changed from the defaults?

**Comment by dnwe** [comment]
On a clean install, El Cap had an empty `/etc/sshd_config` for me, so one would assume the defaults are those specified in `man sshd_config`. Some of these options already match the defaults, but its safer to be explicit about them just incase.

The options are taken from travis-ci's osx slave config. Essentially these would only permit ssh login using public key authentication against an entry in the given $USER's authorized_keys file, all other forms of password-based auth are disabled.

**Comment by dnwe** [comment]
Assuming that the defaults mentioned in the manpage are correct, you could get away with this minimal set to only ensure that password-based login is disabled

```
sudo tee /etc/sshd_config <<EOF
PasswordAuthentication no
ChallengeResponseAuthentication no
UsePAM no
EOF
```

**Comment by mikemcquaid** [comment]
Interesting. One of the things I'm trying to do with Strap, though, is not enable any services by default that users might not need. That's even more secure than a secure SSH configuration :wink:. Nice idea, though!

**Comment by dnwe** [comment]
:+1:
