### ISSUE TITLE
Prompt ssh-add in git@github.com:username/repo.git

### ISSUE THREAD

**Issue by pachoyan** [MikeMcQuaid/strap#140]
It could be a good idea to add an ssh-add prompt if `strap` detects there is a `brew tap` using a ssh from `GitHub`.
For example, if your `Brewfile` has something like:
    tap "homebrew/repo", "git@github.com:username/repo.git"

Then, just prompt a `ssh-add` which can specify to load all you keychain public keys (by default) or a type a file and then it will ask for the password.

**Comment by MikeMcQuaid** [comment]
Given Strap is meant to be the first thing you run on your computer and installs e.g. dotfiles etc. with SSH configuration I think this is something that needs to be done (along with setting up SSH keys) after Strap is run rather than during.
