### ISSUE TITLE
After moving from Boxen to Strap, global ~/.gitconfig file still references nonexistent Boxen gitignore file

### ISSUE THREAD

**Issue by henscu** [MikeMcQuaid/strap#141]
I just moved from Boxen to Strap using the procedure recommended at https://strap.githubapp.com/

Shortly after, I ran a `git status` command on a Git repo which had no changes on my Macbook, and the following Mac/OSX system files in my repo showed up as untracked:

```
.DS_Store
web/.DS_Store
web/app/.DS_Store
```
I was confused, as my `~/.gitignore_global`  file contained the correct exclusions:

```
*~
.DS_Store
```

So, I found how to track the issue down using a command mentioned in this Stackoverflow answer: https://stackoverflow.com/questions/9436405/git-is-ignoring-files-that-arent-in-gitignore

The command is this one, which returns the location of the Git global excludes file:

```git config core.excludesfile```

This showed my global git excludes file to be:  `/opt/boxen/config/git/gitignore`, which did not exist any more, as I had just uninstalled Boxen. The incorrect reference to this file was in `~/.gitconfig` as follows:
```
[core]
        excludesfile = /opt/boxen/config/git/gitignore
```
So to fix my problem, I simply replaced the above Boxen reference in `~/.gitconfig` with the correct one as follows:
```
[core]
        excludesfile = ~/.gitignore_global
```
And, job done...
I'm writing this up here for others as it's a simple fix. Not sure if it's worth incorporating into Strap.

**Comment by MikeMcQuaid** [comment]
Sorry, I missed this before.

> Not sure if it's worth incorporating into Strap.

Agreed 👍
