### ISSUE TITLE
Suggestion: Use --verbose for `brew bundle` command

### ISSUE THREAD

**Issue by Taytay** [MikeMcQuaid/strap#153]
First of all, thanks so much for creating and maintaining Strap! This is very helpful!

I have a pretty large `.Brewfile`, and some of my packages take a while to download. Unfortunately, by default, the package that is _being_ installed isn't printed out by `brew`, so I saw this and thought it had hung:

```
Using 1password
Installing alfred
Installing amazon-music
```

It just sat there for a few minutes before I killed it. Well of course it turns out that the next package being installed was Android studio, hence the long wait. So, I changed my local strap file to append `--verbose` to the `brew bundle --global` command. Now I get pretty output and know why it's going slow. Furthermore, the output is _not _ excessive as I feared it might be:

```
Installing muzzle cask. It is not currently installed.
==> Satisfying dependencies
==> Downloading https://muzzleapp.com/binaries/muzzle.zip
######################################################################## 100.0%
==> Verifying checksum for Cask muzzle
==> Installing Cask muzzle
==> Moving App 'Muzzle.app' to '/Applications/Muzzle.app'.
🍺  muzzle was successfully installed!
Installing muzzle
Installing ngrok cask. It is not currently installed.
==> Satisfying dependencies
==> Downloading https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-darwin-amd64.z
######################################################################## 100.0%
==> No checksum defined for Cask ngrok, skipping verification
==> Installing Cask ngrok
==> Extracting nested container ngrok
==> Linking Binary 'ngrok' to '/usr/local/bin/ngrok'.
🍺  ngrok was successfully installed!
Installing ngrok
```

Thanks again.

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words and suggestion! Strap has intentionally terse output but I'll remember this feedback if others ask for it and consider an option. Thanks!
