### ISSUE TITLE
Suggestion: Don't pipe output of dotfiles/script/setup to dev/null

### ISSUE THREAD

**Issue by Taytay** [MikeMcQuaid/strap#155]
My particular dotfiles/script/setup (https://github.com/Taytay/dotfiles/blob/master/script/setup#L34) had a user prompt in it to ask if you are sure you want to continue (since it might overwrite some settings). When I was running strap for the first time, it started to run my setup script and hung. Only later did I realize what was happening.

You mentioned in another issue (#153) that you prefer minimal output. 
That makes sense to me, but it does limit what we are allowed to do with our dotfiles setup scripts. 
Another option might be to _not_ pipe all of this stuff to dev/null in --debug or a new --verbose mode? If you are open to that, I would be happy to open a PR.

I'm also happy to let this lie for a few years until I provision my next Macbook in 2022. :)

**Comment by MikeMcQuaid** [comment]
> Another option might be to not pipe all of this stuff to dev/null in --debug or a new --verbose mode?

A `--verbose` mode would make sense if it can be done with a (relatively) minimal diff 👍
