### ISSUE TITLE
Adjust CLT package search

### ISSUE THREAD

**Issue by ajz** [MikeMcQuaid/strap#156]
Howdy,

On a new MBP running 10.13.6, when strap gets to installing the Xcode Command Line Tools, it ends up installing a package for El Capitan 10.11 initially for a combination of two reasons that I can see.

1. At least at the moment on 10.13, a softwareupdate search with the installondemand file returns multiple results (verified on two machines):

```
Software Update found the following new or updated software:
   * Command Line Tools (macOS El Capitan version 10.11) for Xcode-8.2
	Command Line Tools (macOS El Capitan version 10.11) for Xcode (8.2), 150374K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.3
	Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.3), 187312K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4
	Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.4), 187380K [recommended]
   * Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4
	Command Line Tools (macOS High Sierra version 10.13) for Xcode (9.4), 187364K [recommended]
```

2. The last part of the CLT_PACKAGE variable is set using `head -n1`.

I'm not sure what to do about item 1 (or if Apple will fix that at some point), but I did notice that [Homebrew's installer](https://github.com/Homebrew/install/blob/052743dae1c004829c02e1a7c0b4aa82eff18846/install#L302) uses `tail -n1` so it picks the last matching update.

* Is there a reason not to switch from head to tail for CLT_PACKAGE?
* I thought maybe also expanding to filter on the macOS major.minor version, but I'm not sure if that's backwards compatible to the package names Apple uses back to 10.9 (I only have 10.12 and 10.13 handy–though I can confirm on 10.12 I only see 10.12 options).

Example:
```
MACOS_MAJMIN=$(sw_vers -productVersion | cut -d "." -f 1,2)
CLT_PACKAGE=$(softwareupdate -l | \
              grep -B 1 -E "Command Line (Developer|Tools)" | \
              awk -F"*" '/^ +\*/ {print $2}' | sed 's/^ *//' | \
              grep $MACOS_MAJMIN | sort -r | head -n1)
```

**Comment by MikeMcQuaid** [comment]
> Is there a reason not to switch from head to tail for CLT_PACKAGE?

I don't think so, that seems like the best course of action 👍.



> I thought maybe also expanding to filter on the macOS major.minor version, but I'm not sure if that's backwards compatible to the package names Apple uses back to 10.9 (I only have 10.12 and 10.13 handy–though I can confirm on 10.12 I only see 10.12 options).

I think if `tail` fixes the issue that'd be sufficient. 

Fancy sending a PR? No worries if not. Thanks again!
