### ISSUE TITLE
Thanks, and a question on composability

### ISSUE THREAD

**Issue by rypit** [MikeMcQuaid/strap#160]
## First of all, thank you.
Thanks for sharing such an excellent tool! About a year ago we were searching for a replacement for boxen @customink, and came across [your blog post](https://mikemcquaid.com/2016/06/15/replacing-boxen/) detailing strap. 

We've found that strap and your recommendation of [Github's Scripts to Rule them All](https://github.com/github/scripts-to-rule-them-all) to be a potent combination! After getting ~100+ apps "strapped"  our team is super productive, application setup is a breeze, and environmental issues have become a thing of the past. All thanks to strap, homebrew, and features such as Brewfile support.

We've also adopted to leverage our strap scripts in continuous integration, which ends up being such a virtuous cycle. The same scripts we set up our dev environments are also used in test -- keeping everything up to date and ensuring that new developer experience is smooth out of the box.

## On composability
We've found that strap has quite a number of advantages of boxen including that it's lightweight, easy to understand for pretty much everybody (no learning puppet), and with the convention of scripts to rule them all encourages that configuration live alongside the application code (previously, we had attempted to do this in a centralized our-boxen repo). We used to maintain a fork of our-boxen which we'd incrementally pull changes from the official branch. While it was convenient to pull those changes from upstream, we eventually started running into frequent merge conflicts and the like. We originally took the same approach when we decided to dive into strap during a hackathon last year. However, as more engineers started "strapping up", we realized that our fork had again become stale. 

Luckily because of how strap has been written, I've recently been able to put together an update to our internal fork that leverages the official strap repo, and layers our customizations on top (We do things like including an organization Brewfile, VPN configuration, and some service configurations that apply for all applications in our organization). 

So how we're using strap now looks something like this:

* An engineer clones our internal fork of strap and executes `bin/bootstrap`.
* Our customized `bin/bootstrap` prompts the engineer for their GitHub credentials in the old way, and sets up the proper shell variables afterwards (or does nothing if we see they've already set up with osxkeychain).
* Our customized `bin/bootstrap` then clones the official strap repo (at its current version) into `~/.strap` (or checks out a specific version if it's already been cloned) then executes the official `bin/bootstrap`.
* Our customized script `bin/bootstrap` then runs our own custom commands such as brew installing from our repo's "organizational" `Brewfile`, etc.

One issue we did end up running into was that we're still recommending that engineers install by cloning our fork rather than through the web interface.

The questions I have are:
* How do you feel with about the above approach? Do you have an alternate recommendation that might work better or better align with your vision for strap?
* If you are ok with this approach, would you be interested in PRs that would aid in the composability of strap, such as [wrapping commands in functions](https://github.com/MikeMcQuaid/strap/compare/master...rypit:rypit/wrap_github?expand=1&w=1)?

Thanks again! 

cc'ing some co-maintainers of our internal fork here so that they can keep up to date:
@chmurph2 @metaskills @dmeiz @a-maas @johnbhall

**Comment by MikeMcQuaid** [comment]
Thanks for the kind words! I also find it to be a good system.

> How do you feel with about the above approach? Do you have an alternate recommendation that might work better or better align with your vision for strap?

Personally I have a hatred of organisational `Brewfile`s because I think you end up forcing things to be installed on users who don't want/need them and because it means the `Brewfile` dependencies in a given repository are not complete/correct. That said, you can hook into this stuff more now using `CUSTOM_HOMEBREW_TAP` and `CUSTOM_BREW_COMMAND` variables which should allow you to push more of your third-party logic into things that can be called by Strap instead of your current fork system.

> If you are ok with this approach, would you be interested in PRs that would aid in the composability of strap, such as wrapping commands in functions?

I'm not sure what you mean by "composability" here. The referenced PR doesn't seem like it would add any value to vanilla Strap itself whilst making the code more complex so I'd probably reject it unless it came with a decent test suite. I'd be most interested in PRs that allow Strap to call out to your custom code rather than customising Strap itself or having third-party code call Strap.

Closing because there's nothing actionable here for me as-is but let's keep talking here. Thanks again!

**Comment by MikeMcQuaid** [comment]
> One such organizational dependency we are considering now is adding pyenv. We'd be happy to share that with homebrew-bootstrap if you think there's an appetite, otherwise it would feel right at home in our own tap.

I don't really maintain homebrew-bootstrap but GitHub uses Python so little internally I think it's a better fit for your own tap.



> Thanks again for taking the time to respond and for your thoughtful suggestions (and of course, for strap itself)!

And thank you for the kind words!
