### ISSUE TITLE
Create and Push SSH Keys to Github

### ISSUE THREAD

**Issue by AlJohri** [mikemcquaid/strap#17]
I like the idea of using a web service to integrate with Github. Perhaps go a step further and (1) create ssh keys and (2) automatically push them to Github?

```bash
if [ ! -f "$HOME/.ssh/id_rsa" ]; then
    ssh-keygen -t rsa -C "$STRAP_GIT_EMAIL"
    eval "$(ssh-agent -s)"
    ssh-add "$HOME/.ssh/id_rsa"    
    COMPUTER_NAME=$(scutil --get ComputerName)
    PUBLIC_KEY=$(cat "$HOME/.ssh/id_rsa.pub")
    curl -u "$STRAP_GITHUB_USER" --data '{"title":"'"$COMPUTER_NAME"'","key":"'"$PUBLIC_KEY"'"}' https://api.github.com/user/keys
fi
```

**Comment by mikemcquaid** [comment]
I think it's nicer as-is just using HTTP. Nice idea, though; I do like it but just trying to keep Strap super-minimal.

**Comment by AlJohri** [comment]
what is the benefit of using `git-credential-osxkeychain` versus ssh?

**Comment by mikemcquaid** [comment]
I believe HTTP is still marginally more performant, it works over proxies and internet connections with blocked ports.
