### ISSUE TITLE
Idempotency?

### ISSUE THREAD

**Issue by AlJohri** [mikemcquaid/strap#18]
Although it would make the script a tad more complicated, are you interested in making strap idempotent? Installing each component would check if the component already exists.

It would allow users who already have homebrew installed or any other component to still run the script without errors.

```bash
if ! command -v brew >/dev/null; then
  # ... install homebrew
else
  echo "Homebrew already installed. Skipping ..."
fi
```

see https://github.com/thoughtbot/laptop for reference

**Comment by mikemcquaid** [comment]
It should already be idempotent (although that's not a noted feature). If there's anywhere you notice it isn't, please detail in this issue as a comment. Thanks!

**Comment by AlJohri** [comment]
Awesome, I just ran the script and it works great :)

Ran the script once or twice just to check idempotency. Seems a tad slow on the "Installing Homebrew" step (given it already exists), but nothing egregious

**Comment by mikemcquaid** [comment]
@AlJohri Yeh, that's the `brew update` taking a wee while.

**Comment by AlJohri** [comment]
I think the script deleted my pythons via pyenv? Will try to reproduce when I get a chance.

**Comment by AlJohri** [comment]
unrelated issue - all is well. sorry for the notifications!

**Comment by blackjid** [comment]
`brew update` is aceptable fast, specially when brew is already up-to-date.
`checking for software updates` is way slower...

**Comment by mikemcquaid** [comment]
@blackjid I think checking for software updates is something that should happen every time.
