### ISSUE TITLE
Does the " 'Found this computer?...' " message need to be double-quoted?

### ISSUE THREAD

**Issue by erikdstock** [MikeMcQuaid/strap#183]
Minor aesthetic question- I love this message but am wondering if it can be safely changed to drop the single quotes that wrap the login message. (also happy to PR it here if you like).

https://github.com/MikeMcQuaid/strap/blob/2c11dc1980a6d2e34897663dc7bca49ec2d1468d/bin/strap.sh#L100

**Comment by MikeMcQuaid** [comment]
Can you send a picture or screenshot of how this shows up on your login screen?

**Comment by erikdstock** [comment]
Sure- thanks. Basically i was just wondering if I could remove these quotes:
![screen shot 2018-10-19 at 1 59 42 pm](https://user-images.githubusercontent.com/9088720/47240724-4848b300-d3b7-11e8-90f8-19c4f5417411.png)

**Comment by MikeMcQuaid** [comment]
Seems like a bug with https://github.com/MikeMcQuaid/strap/pull/152 CC @mistydemeo

**Comment by MikeMcQuaid** [comment]
Fixed in https://github.com/MikeMcQuaid/strap/pull/187
