### ISSUE TITLE
cli interface?

### ISSUE THREAD

**Issue by AlJohri** [mikemcquaid/strap#20]
It would be nice to run strap from the cli and just input the github username / password via stdin. Perhaps I'm misunderstanding the intended audience / purpose of the project.

I figured this was sort of like a bootstrap or normalize.css of personal devops .. the bash script you source before you install your custom Brewfile and symlink your dotfiles etc.

**Comment by mikemcquaid** [comment]
Yup, that makes sense. Would you consider submitting a PR?

**Comment by AlJohri** [comment]
Sure, I'll attempt one during the week.

**Comment by mikemcquaid** [comment]
Thanks! Just to preempt you: make sure it still works non-interactively (e.g. `echo | strap.sh` still behaves and doesn't prompt)

**Comment by mikemcquaid** [comment]
Closing in favour of a future PR.
