### ISSUE TITLE
Chowning spyware causes failures

### ISSUE THREAD

**Issue by mgfreshour** [MikeMcQuaid/strap#207]
Strap will fail if sentinelctl is installed in the /usr/local/bin path as it does like to be chown'd.  I found a similar issue here https://github.com/pivotal/workstation-setup/issues/240.

Adding the -f to the chown's solves the problem, but may cause other problems.

**Comment by MikeMcQuaid** [comment]
This is an issue with `sentinelctl` rather than Strap.
