### ISSUE TITLE
Support for custom Brewfile

### ISSUE THREAD

**Issue by blackjid** [mikemcquaid/strap#21]
Have you consider adding support to setup a custom Brewfile.

Or maybe the way to go is just fork the strap repo and add stuff to `$STRAP_BREWFILE` in https://github.com/mikemcquaid/strap/blob/master/bin/strap.sh#L139 ???

**Comment by mikemcquaid** [comment]
I've considered it but I'm not sure how to do so that wouldn't cause errors. Perhaps it could pull from a username/strap-brewfile repository or something? What do you think?

**Comment by blackjid** [comment]
Yes I thought that, but I think it would be awesome to have an organization support also.

With the github integration you already have the username right?? for personal `Brewfile` that would work.

I know you want to keep it simple, but maybe having a ENV variable `STRAP_BREWFILES=username/repo/path-to-Brewfile,organization/repo/path-to-Brewfile` should pull those `Brewfiles` and install them.

For the first run you could ask in the CLI for this vars and the add them to the environment. Maybe to `/etc/launchd.conf` I think...

**Comment by AlJohri** [comment]
Laptop checks for a file "$HOME/.laptop.local" and sources it if it exists. perhaps something similar is good enough to start

**Comment by mikemcquaid** [comment]
@blackjid How does the environment variable get set? I really don't think it's necessary to add them to the environment and I'd prefer Strap remain a zero-configuration tool.

@AlJohri Yeh, the `brew bundle --global` could be a good fit. I guess it feels weird for me if it reads from that file but doesn't actually put it there, though, given it's a mostly one-time script.

**Comment by blackjid** [comment]
You are right, I didn't know about `--global` arg in brew bundle... sound good to use that one. 

Maybe, if you mean zero-configuration for the user...
In the web application configuration you could add and optional variable
```
GLOBAL_BREWFILE=organization/repo/path-to-Brewfile
USER_BREWFILE=username/repo/path-to-Brewfile
```

Those files get pulled, the `GLOBAL_BREWFILE` could go to `$HOME/.Brewfile` and the `USER_BREWFILE` could go to `$HOME/Brewfile`

Then the script run
```
brew bundle --global
brew bundle --file=$HOME/Brewfile
```

**Comment by mikemcquaid** [comment]
@blackjid I probably want to avoid an organisation-wide Brewfile as I think those should be in individual projects. The user Brewfile could be a good idea but it shouldn't be in the web application configuration as that would restrict the web application to a single user. If it just based it off the GitHub username and a default repo name (e.g. `username/homebrew-brewfile` or something) that could work. Would you be up for trying to make a PR for that? No worries if not.

**Comment by blackjid** [comment]
Yes, I was thinking on `USER_BREWFILE=repo/path-to-Brewfile` without the username, just to set a convention..

The idea behind the `Brewfile` files is to have one per-project?? a la `Gemfile` o `package.json` to define project dependencies outside the default language specific dependencies??

**Comment by mikemcquaid** [comment]
> The idea behind the Brewfile files is to have one per-project?? a la Gemfile o package.json to define project dependencies outside the default language specific dependencies??

Yep. See https://github.com/github/scripts-to-rule-them-all/blob/master/script/setup.

**Comment by blackjid** [comment]
I was thinking that this kind of overlaps with a Docker based development workflow. Have you thought of going docker (docker-compose) to fulfill project dependencies???

I'd like going docker and continue using brew bundle to install main dependencies to run docker bases workflows...

**Comment by mikemcquaid** [comment]
I've thought about it but I find using VMs for development pretty terrible.

**Comment by mikemcquaid** [comment]
Closing in favour of the PR: https://github.com/mikemcquaid/strap/pull/27
