### ISSUE TITLE
Strap vs Boxen

### ISSUE THREAD

**Issue by blackjid** [mikemcquaid/strap#22]
Hey, this looks awesome.... so simple yet powerful.

I know you've work on improving boxen, at what point do you think the **Strap** project will replace all boxen funcionality?? What is the motivation over strap having boxen??
thanks!

**Comment by mikemcquaid** [comment]
I'm personally no longer actively working on Boxen. I don't plan for Strap to ever replace all Boxen functionality; I want it to be the simplest thing that works for all OS X developers regardless of whether you use Ruby, C#, Python, Objective-C or something else. I want it to be stay quick and be easy to debug.

I think Boxen will still have it's place if you are happy for it to basically run all of your system package installation for you and have users not manually use e.g. Homebrew or install Java.

**Comment by blackjid** [comment]
thanks!
