### ISSUE TITLE
DNS Problems

### ISSUE THREAD

**Issue by vinkla** [mikemcquaid/strap#24]
Have you experiences any problems when adding domains in the `/etc/hosts` file on El Capitan?

Mine doesn't seem to go through. Could this be something with the FileVault security setup?

**Comment by mikemcquaid** [comment]
It definitely won't be related to FileVault. What do you mean they don't "go through"? Pretty sure this isn't Strap related.

**Comment by vinkla** [comment]
Oh okay. The reason I'm asking why is, lets say I try to point my website `vinkla.com` against another IP address. It doesn't work. It seams like El Capitan doesn't care about my hosts file at all.

**Comment by mikemcquaid** [comment]
Oh, weird. Not Strap though :sob:

**Comment by vinkla** [comment]
Okay, thats good though. Then we know. Thanks anyway.
