### ISSUE TITLE
Add support to enable and disable features

### ISSUE THREAD

**Issue by blackjid** [mikemcquaid/strap#25]
I was thinking that you could add some Environmental Variables for the web application configuration to enable or disable some features.

For example all features could be enabled by default, but if you want to disable full-disk encryption you might add `DISABLE_FULL_DISK_ENCRYPTION=true` to the application configuration.

**Comment by mikemcquaid** [comment]
I'd rather not have configuration like that as it makes it harder to test and I'd prefer Strap be opinionated and minimal. I don't personally see a good reason to not enable full disk encryption for developers.

**Comment by AlJohri** [comment]
You might want to reconsider allowing to disable encryption. I use strap on my macbook pro and air but unfortunately I can't encrypt the hard drive on my hackintosh. All the other features seem neutral.

**Comment by mikemcquaid** [comment]
@AlJohri I'd rather not, sorry.

**Comment by AlJohri** [comment]
@mikemcquaid 

I'm currently maintaining a [fork](https://github.com/AlJohri/strap/commit/162bd7f33691f9f7a873ce8726eb9772d91cff63) because disabling firevault is a hard requirement for my PC/Mac set up

do you have any tips / links for maintaining a fork yet still pulling in upstream changes as they occur with minimal merge conflicts? thanks

p.s. thanks for setting up that deploy to heroku button - forking the script was a cinch!

**Comment by mikemcquaid** [comment]
@AlJohri I'd consider making it a configurable option if you can justify why it's a good idea and why you need it.

**Comment by AlJohri** [comment]
@mikemcquaid 

Filevault is simply incompatible with a Hackintosh system (I built my own box and installed Mac OS X on there).

I understand this is probably pretty out of scope - not too many hackintosh users out there.

**Comment by mikemcquaid** [comment]
Yeh, pretty out of scope I'm afraid. Easiest thing to avoid merge conflicts might be declaring a function at the top of the file called `fdesetup` which always returns `FileVault is On`?

**Comment by am** [comment]
I'm also in the same situation, I use strap on my daily driver (MacBook pro) and wish I could use it on my hackintosh Looking back to this issue there isn't a lot of popularity. Either way reading the sh script I saw this there is a guard to skip encryption on CI:

```
elif [ -n "$STRAP_CI" ]; then
  echo
  logn "Skipping full-disk encryption for CI"
```
Could this be used to install without other side-effects?

Thanks

**Comment by MikeMcQuaid** [comment]
Sorry @am I'm not interested in supporting Hackintoshes.
