### ISSUE TITLE
Support for custom organization-wide brewfile

### ISSUE THREAD

**Issue by blackjid** [mikemcquaid/strap#28]
We've talked about this on #21, you made your point on organization-wide should be per project. I find that true, but there a lot of types of software installable with homebrew. Specially with the addition of casks.

For example it makes sense that a dependency like `mysql` could be defined as a project dependency, but what about `sequel-pro`??? that is not really a dependency but I would find useful to be able to recommend that piece of software to the whole organization via a global brewfile.

Also we've been using boxen for a few years, and I like the idea if having defined a organization-wide required software stack, that everybody should have. Stuff like ruby managers, plugins for ruby managers (same for node, python, etc), also databases and services like redis, elastic search, etc would be preferable to be defined globally. IMHO

**Comment by mikemcquaid** [comment]
So, my objection to the organisation-wide stuff is that it removes the choice from users. It's OK to recommend things to them but I don't agree with enforcing installation on every machine; it takes away user autonomy and makes things like Strap unpopular for doing that enforcement.

I've been using Boxen for a while now too and not having organisation-wide enforcement of such things is a big part of the reason I worked on this project. I'm a Ruby developer so don't need a Python or Node version manager and get annoyed at the wasted diskspace/installation time and general clutter from all this stuff I know I don't need. I hope that explains my reasoning and I'm totally willing to admit that this might not make sense for everyone.
