### ISSUE TITLE
[Feature Request] Run local strap script after installing Brewfile

### ISSUE THREAD

**Issue by AlJohri** [MikeMcQuaid/strap#40]
Hi,

Similar to the laptop script, it would be nice to be able to run a local `~/.strap.local` script or perhaps even a script in the `USER/homebrew-brewfile` or `USER/dotfiles` repo.

```
if [ -f "$HOME/.strap.local" ]; then
  . "$HOME/.strap.local"
fi
```

Essentially my entire setup at the moment is:

1. run strap
2. install Brewfile
3. run a script to configure the stuff installed from Brewfile (rbenv, bundler, pyenv, node, bashrc, zshrc, etc.)

This would make the 3rd step a bit easier. If its not within the scope of the project there are several other ways I can achieve this so let me know.

**Comment by mikemcquaid** [comment]
My main problem with this workflow: how does `.strap.local` get there on first system bootstrap?

**Comment by mikemcquaid** [comment]
> My main problem with this workflow: how does .strap.local get there on first system bootstrap?

Any ideas on this? Closing this out until this is fleshed out.

**Comment by AlJohri** [comment]
@mikemcquaid revisiting this idea again. I just set up my [`homebrew-brewfile`](https://github.com/AlJohri/homebrew-brewfile) repository and its working swimmingly. The only thing left is to run a script to set up rbenv, bundler, heroku, etc.

I'm very much digging this separation between (boot)strapping one's laptop and setting up dotfiles, since dotfiles can be extremely custom and personal.

Similar to how you fetch the user's Brewfile from Github, I think it makes sense to fetch the user's `.strap.local` from Github.

1. Check if a Github user has a `dotfiles` repository. Clone the repository in `~` (and pull changes?).
2. Check if the dotfiles repo has a `.strap.local` file in it. Symlink to `~`.
3. If `~/.strap.local` exists, run the file.

Now the user can setup their `dotfiles` right from the `~/.strap.local` script if they choose. The only assumption being made is that the user will want to clone their dotfiles into `~` which seems like a reasonable assumption. If they have their own procedure for setting up dotfiles they can still go about doing that.

Thoughts?

**Comment by mikemcquaid** [comment]
@AlJohri I think the problem with dotfiles is that I don't think you can assume people want Strap to clone it or where they'd want it installed. I think that's something that's better living in another way or being a default-off configurable option.

**Comment by johndbritton** [comment]
Is there a recommended way to kick off an arbitrary script from Strap? I'd like to be able to install dotfiles and take care of other config.

Ideally there'd be something like [this](https://github.com/MikeMcQuaid/strap/blob/5813c4b28e278e2c8a18d1830c01dbbd07ce14d9/bin/strap.sh#L262-L267) that would let me run arbitrary setup while keeping sudo alive.

I could write a script and have it run strap and then do the things I want, but I haven't been able to figure out a way to avoid authenticating multiple times.

I feel like it'd be nice to have two places to hook in, once at the beginning of the strap run (to put things like `.Brewfile` into place) and once at the end to set up dotfiles and configure things that depend on strap already having been run (like setting the default shell).

**Comment by MikeMcQuaid** [comment]
There is not beyond the [Brewfile hooks](https://github.com/MikeMcQuaid/strap/blob/5813c4b28e278e2c8a18d1830c01dbbd07ce14d9/bin/strap.sh#L244-L260). My main design opposition to adding them is how they are run on first system install. Strap should be the first thing that's run when you open a Terminal on a new system so any hooks would need a way that's standardised per-org rather than per-user to know what to do on a new install. I'm open to ideas to doing that, though? Perhaps a `strap-config` repository or something on the user account?

**Comment by johndbritton** [comment]
> My main design opposition to adding them is how they are run on first system install.

I totally agree with this.

> Perhaps a strap-config repository or something on the user account?

I'd rather not have *another* repository, maybe a recommended way to call strap from another script? Here's what I'm currently doing ([source](https://github.com/johndbritton/dotfiles/blob/master/script/setup)):

```console
bash <(curl -s https://raw.githubusercontent.com/johndbritton/dotfiles/master/script/setup)
```

The only thing I'm not able to accomplish with this setup right now is prompting for the `sudo` password up front. If I pre-auth in my script [like strap does](https://github.com/MikeMcQuaid/strap/blob/5813c4b28e278e2c8a18d1830c01dbbd07ce14d9/bin/strap.sh#L72-L80) and then call strap, I'm still prompted for my password a second time. If I call strap with `sudo` I get a message saying that strap must be run as your normal user (which makes sense).

What do you think about my approach of wrapping strap? Any recommendation to get around the need to enter my password multiple times?

**Comment by MikeMcQuaid** [comment]
> I'd rather not have another repository, maybe a recommended way to call strap from another script? Here's what I'm currently doing (source):
> 
> bash <(curl -s https://raw.githubusercontent.com/johndbritton/dotfiles/master/script/setup)

That approach makes me uneasy without any sort of checksum validation. I'm wondering if `dotfiles` is a sufficiently standard name to use? If so, maybe we just clone it somewhere?

> If I pre-auth in my script like strap does and then call strap, I'm still prompted for my password a second time. If I call strap with sudo I get a message saying that strap must be run as your normal user (which makes sense).

You probably need to remove `sudo -k` which forces sudo to re-ask for the password.

**Comment by johndbritton** [comment]
> I'm wondering if dotfiles is a sufficiently standard name to use?

What about having a default repository name (dotfiles) with a default command to run `script/setup` and accepting an argument or ENV variable in strap to override?

`bin/strap.sh` would run strap and then, if the user has a dotfiles repo it will clone it and run `script/setup`

`DOTFILES_REPO=foo/bar DOTFILES_SETUP=bin/setup.sh bin/strap.sh` would configure the entry point via env.

`bin/strap.sh --dotfiles-repo=foo/bar --dotfiles/setup=bin/setup.sh` would do the same via command line arguments.

This gives the user the ability to set up any repo they want and run a script in that repo after strap finishes.
