### ISSUE TITLE
`tap 'caskroom/cask'` unnecessary?

### ISSUE THREAD

**Issue by croaky** [mikemcquaid/strap#51]
My understanding was it is built into Homebrew now.

https://github.com/caskroom/homebrew-cask/commit/0d290b15e894c8db387f77e2586223368a04fea8

https://github.com/thoughtbot/laptop/commit/c92c7adc7f9079aa670d5e30a0dd2036c8b10fac

**Comment by mikemcquaid** [comment]
Yup, it is :+1:. Will fix this, thanks for the nitpick.

**Comment by mikemcquaid** [comment]
Oh, well, actually, to be more precise: it's not _required_ but it's probably not a bad thing to do as it'll stop the manual tap being done when you run `brew cask`. Basically: it's preloading the tap. I guess it's a question of disk space usage vs. quicker start of `brew cask` on first run.

**Comment by croaky** [comment]
Gotcha, thanks for the explanation. On `thoughtbot/laptop`, we've been learning toward performance lately when making those tradeoffs. Think you're going to keep the line?

**Comment by mikemcquaid** [comment]
@croaky I guess the balance is "performance of first thoughtbot/laptop run" vs "performance of first Homebrew run". I'm not sure what I'm going to do, yet.

**Comment by mikemcquaid** [comment]
Yeh, I'm going to keep doing this; it doesn't slow things down much and it means a future `brew cask` run is instant (which I'd rather optimise for).

**Comment by croaky** [comment]
Sounds good, appreciate hearing your thinking.
