### ISSUE TITLE
Xcode Command Lines Tools necessary?

### ISSUE THREAD

**Issue by croaky** [mikemcquaid/strap#52]
We pulled `xcode-select --install` and `sudo xcodebuild -license` out of `thoughtbot/laptop` around when we were getting it ready to support Mavericks.

Our reasoning was:

> Homebrew's install script checks whether the command line tools are installed,
> and, only if necessary, will run `xcode-select --install`.

It looks like that's still true today:

https://github.com/Homebrew/homebrew/blob/master/bin/brew#L97-L121

The commit was https://github.com/thoughtbot/laptop/commit/3106976ff39f7c591138746a36badb95339d5449 but Homebrew link in commit is old / broken.

It looks like you're seeing a benefit to having them in your script. I see some Issues with conversation talking about having the user re-agree to the license when Xcode is upgraded. Is that the main reason to have them in or are there others?

Hope these questions aren't bugging you; just looking to learn if there are changes to our script we should make, too.

**Comment by mikemcquaid** [comment]
No, these aren't bugging me, happy to answer.

My reasoning is that we're not actually using Homebrew's installer so things could be done in a single script (maybe ironic given I'm a Homebrew maintainer) and I want to ensure that all of these things are installed without requiring user interaction.

**Comment by croaky** [comment]
Gotcha, good reasons. Not having user interaction is nice; we sort of gave up on that, ha.

**Comment by mikemcquaid** [comment]
:+1:
