### ISSUE TITLE
omniauth-github does not return a token with access to organization repository

### ISSUE THREAD

**Issue by isamuelson** [mikemcquaid/strap#57]
https://github.com/intridea/omniauth-github/issues/60

**Comment by mikemcquaid** [comment]
To help me debug this issue can you explain:
- What you were trying to do (and why)
- What happened
- What you expected to happen
- Step-by-step reproduction instructions (with as minimal input data as possible)

**Comment by isamuelson** [comment]
* tried to clone a github repository from an organization I belong to
* repository was not cloned due to an error (not found/no access)
* i expected the repo to be cloned
* run strap.sh, clone a repo from a github organization the user belongs to

the token that strap uses does not have access to all the organizations and their repos.

**Comment by spraints** [comment]
@isamuelson does the organization have [application policies](https://developer.github.com/changes/2015-01-19-an-integrators-guide-to-organization-application-policies/) enabled? If so, has the organization approved your strap oauth application?

**Comment by isamuelson** [comment]
I don't see the app at all or was there any email about approving it

On Thursday, March 17, 2016, Matt Burke <notifications@github.com> wrote:

> @isamuelson <https://github.com/isamuelson> does the organization have application
> policies
> <https://developer.github.com/changes/2015-01-19-an-integrators-guide-to-organization-application-policies/>
> enabled? If so, has the organization approved your strap oauth application?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mikemcquaid/strap/issues/57#issuecomment-197998945>
>


-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by mikemcquaid** [comment]
@isamuelson unless you are an organisation administrator you may not have the ability to give Strap access to that repository. It may make more sense instead to create your own Personal Access Token. Let's keep talking about this but it doesn't seem to be a Strap bug.

**Comment by isamuelson** [comment]
I M an admin and I had not option to do that...strap was never on the list

On Thursday, March 17, 2016, Mike McQuaid <notifications@github.com> wrote:

> Closed #57 <https://github.com/mikemcquaid/strap/issues/57>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mikemcquaid/strap/issues/57#event-594281669>
>


-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by mikemcquaid** [comment]
@isamuelson Does the organization have [application policies](https://developer.github.com/changes/2015-01-19-an-integrators-guide-to-organization-application-policies/) enabled?

**Comment by isamuelson** [comment]
Yes. I have other apps there

On Friday, March 18, 2016, Mike McQuaid <notifications@github.com> wrote:

> @isamuelson <https://github.com/isamuelson> Does the organization have application
> policies
> <https://developer.github.com/changes/2015-01-19-an-integrators-guide-to-organization-application-policies/>
> enabled?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mikemcquaid/strap/issues/57#issuecomment-198212107>
>


-- 

*Ido Samuelson*

Phone (US): +1-415-562-8582

Email: *ido.samuelson@gmail.com*
LinkedIn: http://www.linkedin.com/in/isamuelson

Skype: ido_samuelson

**Comment by mikemcquaid** [comment]
If you've enabled application policies check the list of apps enabled or disabled for the org.

**Comment by isamuelson** [comment]
closing the issue...token was cached...once i cleared the cache i was able to approve the organization

**Comment by mikemcquaid** [comment]
Thanks for letting me know @isamuelson!
