### ISSUE TITLE
strap pf rules incompatible with xhyve networking

### ISSUE THREAD

**Issue by grantr** [mikemcquaid/strap#64]
[xhyve](https://github.com/mist64/xhyve) is an OSX virtualization solution that's lighter weight than QEMU and VirtualBox. It's a promising option for running containers on OSX.

Strap's `pf` rules for forwarding HTTP/S ports cause outbound connections from VMs to ports 80 and 443 to be misrouted.

Here's the effect from inside the VM:

```
$ curl -s github.com | head
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
```

Running `sudo pfctl -F all -a dev.strap` to unload the rules for the `dev.strap` anchor fixes the problem (after stopping and starting the VM):

```
$ curl -sv github.com | head
* Rebuilt URL to: github.com/
*   Trying 192.30.252.131...
* Connected to github.com (192.30.252.131) port 80 (#0)
> GET / HTTP/1.1
> Host: github.com
> User-Agent: curl/7.47.1
> Accept: */*
>
< HTTP/1.1 301 Moved Permanently
< Content-length: 0
< Location: https://github.com/
< Connection: close
<
* Closing connection 0
```

Strap's `pf` rules are:

```
rdr pass inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8443
```

I'm not sure what needs to change, but my guess is `any to any` is too broad.

**Comment by mikemcquaid** [comment]
> I'm not sure what needs to change, but my guess is any to any is too broad.

I'm definitely up for including a fix here but as I don't use `xhyve` currently I think I'll need to request a pull request for a fix here. Sorry and thanks for the report.
