### ISSUE TITLE
Prevent upgrading operating system in system update

### ISSUE THREAD

**Issue by AlJohri** [mikemcquaid/strap#66]
`sudo softwareupdate --install --all`

My OS just upgraded by running strap. Did not realize an upgrade was in progress and I did a hard shut down. Might want to at least warn users that its a possibility if not prevent it.

P.S. My macbook seems fine but I don't know how to verify the integrity of the update.

**Comment by mikemcquaid** [comment]
This is an intentional, documented security feature so I'm afraid I'm going to pass on this change.

**Comment by AlJohri** [comment]
Fair enough. I was just not expecting an OS update
