### ISSUE TITLE
Opt-out OSX customizations

### ISSUE THREAD

**Issue by kassio** [mikemcquaid/strap#67]
The OSX customizations are nice, but in my case I'd like to opt-out some of them.

I'd be glad to open a pull request with this modification. What do you think in use env variables to opt-out these, something like: `STRAP_ACTIVE_FIREWALL=0`?

**Comment by mikemcquaid** [comment]
@kassio Server-side environment variables seem like a good fit. Let's discuss in here what things you would like to opt-out of so you can more easily make your PR. Can you list them? Thanks!

**Comment by kassio** [comment]
I'd like to opt-out these ones:

- Enables the OS X application firewall (for better security)
- Adds a Found this computer? message to the login screen (for machine recovery)
- Forwards localhost port 80 to 8080 and 443 to 8443 (for running web servers as an unprivileged user)

**Comment by mikemcquaid** [comment]
Could you elaborate a little on why for each? Also interested in that, thanks!

**Comment by kassio** [comment]
I have the same reason for all: I have two computers, one that is my work computer and other that is my home computer. 
The last one it's not only my, it's like a family computer, but sometime I do some development on it. And I'd like to keep both updated and with some dev tools installed, however the home one I don't need firewall or port forwarding. Also, because it's a home computer, the `Found this computer` is not required.

**Comment by mikemcquaid** [comment]
When you say "home computer" do you mean "not a laptop"? I wonder if there's a way to detect a machine not being a laptop for the `Found this computer` stuff; I think that would be preferable.

For the others: yeh, an environment variable for the web interface seems reasonable 👍

**Comment by AlJohri** [comment]
how is this different from #25 ?

**Comment by mikemcquaid** [comment]
@AlJohri Partly time passing and more people asking for things, partly the features being requested and partly (my understanding of this) being something that's customised in the web app by "administrators" rather than the script by "end-users".

**Comment by kassio** [comment]
@mikemcquaid I was looking better the script. And, for my needs, I can use the `STRAP_CI`. It won't disable the `Found computer`, but that's not a problem to me.
Also, when I opened this, I wasn't thinking in change this in the web app. I can see now that I wasn't clear about that, but my intentions was to change this on the CLI.

Thank you anyway for the help.
