### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by DoomHammer** [mikemcquaid/strap#68]
Hi!

I have been searching for something like this for a while now. Problem is I mainly (which at the moment means exclusively) use Linux. I have been working on a personal fork that works on Linux (mostly skipping `defaults write` and `osxkeychain` stuff). Would you be willing to accept a PR at some point or is this project strictly OS X?

Thanks,
Piotr

**Comment by mikemcquaid** [comment]
@DoomHammer I think I'd want to see more than a couple of users for this before I'd be happy with integrating Linux support. Given so much of this is OS X-specific I'm not really sure in the value, personally. Do keep in touch, though, and let me know if there's stuff I can do to make running a fork easier.

**Comment by DoomHammer** [comment]
Sure, totally understood :)
