### ISSUE TITLE
More security related stuff

### ISSUE THREAD

**Issue by joewilliams** [mikemcquaid/strap#8]
This is a great guide for OSX security, perhaps more of it could be integrated into strap?

https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide

**Comment by mikemcquaid** [comment]
The stuff that jumped out at me was the application level firewall and screensaver password delay. Did you have any other specific thoughts?

**Comment by joewilliams** [comment]
Something like https://www.obdev.at/products/littlesnitch/index.html is really handy but is not free.

Also the following are pretty good too:
* https://fix-macosx.com/
* https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide#certificate-authorities
* https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide#curl
* https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide#openssl

**Comment by mikemcquaid** [comment]
> https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide#openssl

Just submitted an issue about this as it can make your security worse rather than better: https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide/issues/39

> Something like https://www.obdev.at/products/littlesnitch/index.html is really handy but is not free.
> 
> Also the following are pretty good too:
> 
> https://fix-macosx.com/
> https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide#certificate-authorities
> https://github.com/drduh/OS-X-Yosemite-Security-and-Privacy-Guide#curl

This stuff is a bit too opinionated for what I'm going for with Strap but appreciate the heads-up.

**Comment by joewilliams** [comment]
Cool, np.

**Comment by mikemcquaid** [comment]
Let's leave this open, gonna tackle some of the application level firewall and screensaver stuff.
