### ISSUE TITLE
Auth token access restriction caveat is not noted

### ISSUE THREAD

**Issue by ticky** [MikeMcQuaid/strap#85]
GitHub permissions granted to Strap are then granted to the computer it's used on, and thusly if the token lacks access to private/organisation repositories, the computer will lack access to them!

It might be worth adding this to the documentation.

cc @mistydemeo

**Comment by MikeMcQuaid** [comment]
Fixed. Thanks for the PR!

**Comment by MikeMcQuaid** [comment]
Er, for the issue 😆.

**Comment by ticky** [comment]
This might be worth adding to the public site itself, as @mistydemeo just sent me there, and I'd have missed the Readme altogether (but I did read the script to make sure it didn't do anything nasty before executing it :wink:)!

**Comment by MikeMcQuaid** [comment]
@ticky good idea!

**Comment by MikeMcQuaid** [comment]
(although I now blame this bug on @mistydemeo 😆 😉 )

**Comment by MikeMcQuaid** [comment]
Reclosed by https://github.com/MikeMcQuaid/strap/pull/86.
