### ISSUE TITLE
Too many development-unrelated features

### ISSUE THREAD

**Issue by bfred-it** [MikeMcQuaid/strap#87]
Straps is touted as a "minimal bootstrap", but enabling full-disk encryption is far from necessary, for one. I'd say these features don't belong here:

- Disables Java in Safari (for better security)
- Enables the OS X screensaver password immediately (for better security)
- Enables the OS X application firewall (for better security)
- Adds a `Found this computer?` message to the login screen (for machine recovery)
- Enables full-disk encryption and saves the FileVault Recovery Key to the Desktop (for better security)
- Installs the latest OS X software updates (for better security)

**Comment by MikeMcQuaid** [comment]
You've highlighted literally every security-related feature. I consider them all important and minimal so will leave them in. Thanks for the issue, anyway ❤️
