### ISSUE TITLE
Replacing Boxen

### ISSUE THREAD

**Issue by thompsongl** [MikeMcQuaid/strap#88]
We currently have an shared, organizational Boxen setup and are looking to move to something else. Strap _seems_ like the obvious choice. I recently came across your Replacing Boxen post, but I'm not fully clear on how to port shared projects that currently use Boxen's dependency management and nginx config.

Could you provide any insight or point to an example project?

**Comment by MikeMcQuaid** [comment]
There's no public example projects I can point to, unfortunately. Thankfully the project-level complexity is pretty low.

GitHub uses Strap for setting up individual developer machines and all the features for per-user customisation (e.g. install dotfiles, user `Brewfile`, etc.)

Projects share a bunch of logic using a homebrew tap installed by a `Brewfile` (see https://github.com/Homebrew/homebrew-bundle) in the project root. You can see these scripts in https://github.com/github/homebrew-bootstrap; for example we just add a `.ruby-version` in the project root and call `brew bootstrap-rbenv-ruby` to setup that Ruby version in a way that's shared with other projects.

The project Homebrew/Homebrew Cask/tap dependencies are also specified in that `Brewfile` and installed with `brew bundle`. These are all put together in a `script/bootstrap` file (see https://github.com/github/scripts-to-rule-them-all#scriptbootstrap) which is the only manual entry point for a user.

Hopefully that explains a bit but I'm happy to answer any more questions here.

**Comment by thompsongl** [comment]
Thanks for the help, Mike. I'll probably give it a go this weekend and get back if I have any questions.

**Comment by MikeMcQuaid** [comment]
My pleasure, sounds good.
