### ISSUE TITLE
Personal vs Work

### ISSUE THREAD

**Issue by thegiantbeast** [MikeMcQuaid/strap#91]
@MikeMcQuaid would you consider/accept a `--branch myBrang` option as a PR?

My use case is that although your workflow simplifies a lot of the setup (thanks for that btw) it doesn't consider the fact that work setups might not be exactly the same as personal ones.
Normally you (may) use more recent technologies as you may be experimenting new stuff before applying at work or something like that.

So the idea is that the repos *homebrew-brewfile* and *dotfiles* could have a *"work"* and *"personal"* branches with different content between them, allowing the possibility of choosing if I want to setup my machine as a *"work"* or *"personal"* one. (being the *master* always the default branch, as it is right now).
Which branch you define as *"work"* or as *"personal"* is up to you, the flag will only allow to set a different branch than *master*.

If you agree, I'll try to create a PR with the change asap.

**Comment by MikeMcQuaid** [comment]
I'm open to an approach that doesn't require the user to perform manual configuration or arguments like `--branch`. If there's an environment variable that could be set on the web application side that'd be the best approach. Alternatively, you could put some of this branching logic inside your `Brewfile` or `dotfiles` themselves.

**Comment by MikeMcQuaid** [comment]
(Closing just because the question is answered, not because I'd never accept this).

**Comment by thegiantbeast** [comment]
Ok, I think I got your idea. So your prefer the concept of someone going to the website download the file and without any further changes or arguments, install and setup everything that's needed it, correct?

So following your thought, would you accept from that page to have an option where you could specify the branch and download the file with that branch injected as a variable (same as github username, etc)?
Or, you think that the branch should be a environment variable which is set on the box where the web app is running and so when fetching the file it would set it at that point?

I'm trying to figure out how you envision the use of this repo, is it a web app that's running on a box where everyone can get the url to download the file or every person would clone this repo and access the file locally?
Maybe I misunderstood the intention of this tool. Hopefully you could clarify it for me.

**Comment by thegiantbeast** [comment]
> Alternatively, you could put some of this branching logic inside your Brewfile or dotfiles themselves.

And to explain why I think your suggestion isn't feasible, on the dotfiles you could put that logic inside the script/setup or script/bootstrap, on the brew bundle side I believe it's not possible (at least that I'm aware of) as you clone the repo and run the bundle command, which as far as I know, doesn't support this kind of logic.
Another thing that I don't like/I believe it's unnecessary, is that its easier to add this logic in one single place than having it spread across dotfiles and Brewfile.

**Comment by MikeMcQuaid** [comment]
> Ok, I think I got your idea. So your prefer the concept of someone going to the website download the file and without any further changes or arguments, install and setup everything that's needed it, correct?

Yes. For the user, Strap should always be zero-configuration. That's a feature I'm not wanting to remove.

> Or, you think that the branch should be a environment variable which is set on the box where the web app is running and so when fetching the file it would set it at that point?

This.

> I'm trying to figure out how you envision the use of this repo, is it a web app that's running on a box where everyone can get the url to download the file or every person would clone this repo and access the file locally?
> Maybe I misunderstood the intention of this tool. Hopefully you could clarify it for me.

The web app is hosted by an organisation whose members use Strap or by a single user wishing to use Strap. They are responsible for configuring it so it can be used in a zero-configuration fashion.

> And to explain why I think your suggestion isn't feasible, on the dotfiles you could put that logic inside the script/setup or script/bootstrap, on the brew bundle side I believe it's not possible (at least that I'm aware of) as you clone the repo and run the bundle command, which as far as I know, doesn't support this kind of logic.

`Brewfile`s are Ruby so anything that's possible in Ruby is possible in them.


> Another thing that I don't like/I believe it's unnecessary, is that its easier to add this logic in one single place than having it spread across dotfiles and Brewfile.

I disagree. It's easier for single users to modify there Brewfile than add code and increase the complexity of the tool for everyone using it.

**Comment by nunofgs** [comment]
@MikeMcQuaid I've had the need to have organization-wide dotfiles as well and largely agree with all your points. In particular, I very much support the following:

* Strap should be zero-conf.
* Any organization-wide setting should be at the web application level, that serves the `strap.sh` file.
* Most organizations have very common needs and configurations that are shared across all employees.
* However, I believe users should be able to override those configs if needed.

With that in mind, I've been trying to think of a way to satisfy the above requirements but could use your input. For example, let's hypothetically say that:

1. An env var `ORGANIZATION=my-company` exists and is deployed on the web app.
2. A user downloads and runs `strap.sh`.
3. Strap would then use the _$ORGANIZATION_ env var to clone the organization wide dotfiles to: `$HOME/.dotfiles-$ORGANIZATION` (or `$HOME/.dotfiles/$ORGANIZATION`, etc.).
4. The user-specific dotfiles (if they exist) should also be fetched (_in my opinion_) and would be cloned to `$HOME/.dotfiles`.
5. After that, the normal `script/setup` and `script/bootstrap` scripts would be executed, first from `$HOME/.dotfiles-$ORGANIZATION`, then `$HOME/.dotfiles`).
6. Brewfiles would be analogous and would be run in sequence (first organization, then user-specific).

While the above process would definitely work, I find it a bit kludgey, especially having to clone the two repos.

I'm happy to submit a PR but would really love your ideas on how to best approach this.

**Comment by MikeMcQuaid** [comment]
> Most organizations have very common needs and configurations that are shared across all employees.

I'm afraid I don't agree with this.

> However, I believe users should be able to override those configs if needed.

This contradicts your above plan. If I work for an organisation that doesn't control every aspect of my system but Strap installs software and configuration I don't want on my system: Strap just became an annoying tool.

Homebrew dependency requirements are per-project rather than per-system. You can replicate a per-system approach but having some of these tools installed on individual projects. If you are not using `Brewfile`s in your projects: you will find Strap lacking.

For the above reasons I'm still 👎 on adding this functionality to Strap, sorry.

**Comment by nunofgs** [comment]
🤔 understood.

Would you accept a PR that displays a page on the web UI asking the user to choose which organization they want to install their dotfiles from? (only organizations with a `dotfiles` repo would be displayed, for example)

**Comment by MikeMcQuaid** [comment]
> Would you accept a PR that displays a page on the web UI asking the user to choose which organization they want to install their dotfiles from? (only organizations with a dotfiles repo would be displayed, for example)

Sorry, I think that's a bit outside the project scope for a relatively niche use-case.

**Comment by nunofgs** [comment]
Forgive me, but from your previous [comment](https://github.com/MikeMcQuaid/strap/issues/91#issuecomment-252479196) it seemed you were open to the idea of supporting organizations in some way.

Has that stance changed?

**Comment by MikeMcQuaid** [comment]
@nunofgs I've disagreed with pretty much everything you've said in here about organisations since your first comment so: sorry, I'm not open to this idea and that's not a change in my stance.
