### ISSUE TITLE
Add permissions for Homebrew cache

### ISSUE THREAD

**Issue by thegiantbeast** [MikeMcQuaid/strap#92]
I believe that the cache folder permissions of homebrew are not set (https://github.com/MikeMcQuaid/strap/blob/master/bin/strap.sh#L198).

I can submit a PR wich sets the permissions to `brew --cache` folder.

**Comment by MikeMcQuaid** [comment]
What do you think they need set to?

**Comment by thegiantbeast** [comment]
@MikeMcQuaid whenever you have multiple users on the same box (which happens to me). The folder should be readable/writable by both.

You can check these sources if you will:
https://gist.github.com/jaibeee/9a4ea6aa9d428bc77925
http://blog.strug.de/2012/06/my-homebrew-multi-user-setup/

The last link goes a bit further and creates a group, but I think there's no need for such "complexity".

**Comment by MikeMcQuaid** [comment]
The default Homebrew cache is single-user. This was a relatively recent change for security reasons: https://github.com/Homebrew/legacy-homebrew/issues/23232. As a result, I'm not wanting to change Strap to do the same, sorry.

**Comment by thegiantbeast** [comment]
I wasn't aware of that, so never mind. Thanks for letting me know.
