### ISSUE TITLE
git credentials

### ISSUE THREAD

**Issue by alexmace** [MikeMcQuaid/strap#93]
I'm having trouble with strap recording my Git credentials, which I think I have narrowed down to this code:

```
if git credential-osxkeychain 2>&1 | grep $Q "git.credential-osxkeychain"
then
```

When I run `git credential-osxkeychain 2>&1`, the output doesn't contain git.credential-osxkeychain, so that statement is never satisfied:

```
➜  strap git:(feature/setup-oh-my-zsh) ✗ git credential-osxkeychain 2>&1
usage: git credential-osxkeychain <get|store|erase>
```

I might be misreading it, but I believe the grep $Q is gripping the output of the previous command.

If so, should it actually be checking for "git credential-osxkeychain"? or have I missed something and should be getting different output?

This is on macOS Sierra, using git 2.10.2 installed via Homebrew.

Many thanks for your help and this project!

**Comment by MikeMcQuaid** [comment]
> When I run git credential-osxkeychain 2>&1, the output doesn't contain git.credential-osxkeychain, so that statement is never satisfied:

The `.` in this case is parsed by `grep` as being any character so ` ` or `-` will both work (in your case the prior will match).

**Comment by alexmace** [comment]
Where's the facepalm emoji, I should have realised that!

Thanks, I'll close this and go back to scratching my head about the real problem.
