### ISSUE TITLE
Post Brewfile install hooks?

### ISSUE THREAD

**Issue by neonsamurai** [MikeMcQuaid/strap#94]
Hi Mike,

first of all: thanks for the great script!. It helped me a lot already. However I wondered if you could provide something like post Brewfile install scripts? Or maybe there is already a way to run configuration scripts after the Brew/Cask packages have been installed?

I am speaking of things like creating database users, running configuration scripts for iterm2 and similar things. If not I could provide a pull request.

Cheers and happy coding,
Tim

**Comment by MikeMcQuaid** [comment]
Where would these hooks live, out of interest?

**Comment by MikeMcQuaid** [comment]
Just to set expectations: I'm unlikely to include this as I think it's a better fit for https://github.com/github/scripts-to-rule-them-all i.e. have a script that calls `brew bundle` etc. rather than the other way around.

**Comment by neonsamurai** [comment]
Ok so when thinking about it, I think it would be sufficient to move the 'Setup dotfiles' section to after the 'Install local Brewfile' section in `bin/strap.sh`. No new hooks needed really. This way you would have all the dependent tools installed and could run custom configuration on the via `script/boostrap, script/setup`.

**Comment by MikeMcQuaid** [comment]
That's not going to work unfortunately because it's a feature to allow people to install from their `Brewfile` in their dotfiles.

**Comment by neonsamurai** [comment]
Oh I see so installing the Brewfile from the homebrew-brewfile repository is more of an optional thing?

**Comment by MikeMcQuaid** [comment]
Yeh, it predated the dotfiles installation and is mostly only useful for people now who don't have a dotfiles repo.

**Comment by shaneog** [comment]
@MikeMcQuaid I didn't realise that - I actually set up a `homebrew-brewfile` repo just for Strap, even though I already have my `dotfiles` repo.
I think , it would be worth adding this recommendation (Brewfile in inside your dotfiles repo) to the README. 
Would you like me to create a PR?

**Comment by MikeMcQuaid** [comment]
Yeh, a PR would be good, thanks.

**Comment by AlJohri** [comment]
@MikeMcQuaid if I call `brew bundle` in my `scripts/setup` can I make it so strap doesn't do `brew bundle`? seems like a pretty common use case to do post install stuff like setting up rbenv versions etc.

**Comment by MikeMcQuaid** [comment]
@AlJohri No, I'd rather have strap call `brew bundle`. `brew bundle check` could be used to speed things up so Strap's is a no-op and yours does the actual work.

**Comment by AlJohri** [comment]
Cool, sounds good to me

**Comment by MikeMcQuaid** [comment]
Cool. A PR would be great as it's not related to this issue.
