### ISSUE TITLE
Why not use sudo -v?

### ISSUE THREAD

**Issue by superstrong** [MikeMcQuaid/strap#99]
I'm incorporating parts of your script into our own company setup script, and a peer is asking why you use this instead of `sudo -v`:

> This seems strange compared to simply running something like `sudo true` to avoid breaking encapsulation. Why `touch` this manually?

```
if [ "$1" = "--sudo-wait" ]; then
  while true; do
    mkdir -p "/var/db/sudo/$SUDO_USER"
    touch "/var/db/sudo/$SUDO_USER"
    sleep 1
  done
  exit 0
fi
```

**Comment by superstrong** [comment]
Aha, I just saw https://github.com/MikeMcQuaid/strap/pull/42 -- closing this.

**Comment by MikeMcQuaid** [comment]
@superstrong Cool. Please ensure your company complies with the MIT license 😉

**Comment by superstrong** [comment]
Of course :)

Actually, another question about this: If you avoid spawning the child process as sudo, can you then use `sudo -v` to keep it alive? (Do you _need_ to spawn the child process as sudo?)

**Comment by MikeMcQuaid** [comment]
> Actually, another question about this: If you avoid spawning the child process as sudo, can you then use sudo -v to keep it alive? (Do you need to spawn the child process as sudo?)

Possibly, yeh. If you submit a PR I'll happily try it out 😉
